--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: gui-driver
  name: gui-driver
  namespace: default
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: gui-driver
  template: 
    metadata: 
      labels: 
        app: gui-driver
    spec: 
      containers: 
        - 
          image: "us.gcr.io/course-project-330721/pob6/gui_driver:latest"
          name: gui-driver-1
--- 
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  labels: 
    app: gui-driver
  name: gui-driver-hpa-zmzw
  namespace: default
spec: 
  maxReplicas: 5
  metrics: 
    - 
      resource: 
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: gui-driver
