--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    cloud.google.com/neg: "{\"ingress\":true}"
  finalizers: 
    - service.kubernetes.io/load-balancer-cleanup
  labels: 
    app: hadoop-namenode
  managedFields: 
    - 
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1: 
        ? "f:metadata"
        : 
          ? "f:labels"
          : 
            ? "."
            : {}
            ? "f:app"
            : {}
        ? "f:spec"
        : 
          ? "f:externalTrafficPolicy"
          : {}
          ? "f:ports"
          : 
            ? "."
            : {}
            ? "k:{\"port\":9000,\"protocol\":\"TCP\"}"
            : 
              ? "."
              : {}
              ? "f:name"
              : {}
              ? "f:port"
              : {}
              ? "f:protocol"
              : {}
              ? "f:targetPort"
              : {}
            ? "k:{\"port\":9870,\"protocol\":\"TCP\"}"
            : 
              ? "."
              : {}
              ? "f:name"
              : {}
              ? "f:port"
              : {}
              ? "f:protocol"
              : {}
              ? "f:targetPort"
              : {}
          ? "f:selector"
          : 
            ? "."
            : {}
            ? "f:app"
            : {}
          ? "f:sessionAffinity"
          : {}
          ? "f:type"
          : {}
      manager: GoogleCloudConsole
      operation: Update
    - 
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1: 
        ? "f:metadata"
        : 
          ? "f:finalizers"
          : 
            ? "."
            : {}
            ? "v:\"service.kubernetes.io/load-balancer-cleanup\""
            : {}
        ? "f:status"
        : 
          ? "f:loadBalancer"
          : 
            ? "f:ingress"
            : {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-11-28T17:17:56Z"
  name: hadoop-namenode-service
  namespace: default
spec: 
  externalTrafficPolicy: Cluster
  ipFamilies: 
    - IPv4
  ipFamilyPolicy: SingleStack
  ports: 
    - 
      name: 9870-to-9870-tcp
      nodePort: 31029
      port: 9870
      protocol: TCP
      targetPort: 9870
    - 
      name: 9000-to-9000-tcp
      nodePort: 30212
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector: 
    app: hadoop-namenode
  sessionAffinity: None
  type: LoadBalancer
