--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels: 
    app: hadoop-namenode
  managedFields: 
    - 
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1: 
        ? "f:metadata"
        : 
          ? "f:labels"
          : 
            ? "."
            : {}
            ? "f:app"
            : {}
        ? "f:spec"
        : 
          ? "f:progressDeadlineSeconds"
          : {}
          ? "f:replicas"
          : {}
          ? "f:revisionHistoryLimit"
          : {}
          ? "f:selector"
          : {}
          ? "f:strategy"
          : 
            ? "f:rollingUpdate"
            : 
              ? "."
              : {}
              ? "f:maxSurge"
              : {}
              ? "f:maxUnavailable"
              : {}
            ? "f:type"
            : {}
          ? "f:template"
          : 
            ? "f:metadata"
            : 
              ? "f:labels"
              : 
                ? "."
                : {}
                ? "f:app"
                : {}
            ? "f:spec"
            : 
              ? "f:containers"
              : 
                ? "k:{\"name\":\"hadoop-namenode-1\"}"
                : 
                  ? "."
                  : {}
                  ? "f:env"
                  : 
                    ? "."
                    : {}
                    ? "k:{\"name\":\"CLUSTER_NAME\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"CORE_CONF_fs_defaultFS\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"CORE_CONF_hadoop_http_staticuser_user\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"CORE_CONF_hadoop_proxyuser_hue_groups\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"CORE_CONF_hadoop_proxyuser_hue_hosts\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"CORE_CONF_io_compression_codecs\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"HDFS_CONF_dfs_permissions_enabled\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                    ? "k:{\"name\":\"HDFS_CONF_dfs_webhdfs_enabled\"}"
                    : 
                      ? "."
                      : {}
                      ? "f:name"
                      : {}
                      ? "f:valueFrom"
                      : 
                        ? "."
                        : {}
                        ? "f:configMapKeyRef"
                        : 
                          ? "."
                          : {}
                          ? "f:key"
                          : {}
                          ? "f:name"
                          : {}
                  ? "f:image"
                  : {}
                  ? "f:imagePullPolicy"
                  : {}
                  ? "f:name"
                  : {}
                  ? "f:resources"
                  : {}
                  ? "f:terminationMessagePath"
                  : {}
                  ? "f:terminationMessagePolicy"
                  : {}
              ? "f:dnsPolicy"
              : {}
              ? "f:restartPolicy"
              : {}
              ? "f:schedulerName"
              : {}
              ? "f:securityContext"
              : {}
              ? "f:terminationGracePeriodSeconds"
              : {}
      manager: GoogleCloudConsole
      operation: Update
    - 
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1: 
        ? "f:metadata"
        : 
          ? "f:annotations"
          : 
            ? "."
            : {}
            ? "f:deployment.kubernetes.io/revision"
            : {}
        ? "f:status"
        : 
          ? "f:availableReplicas"
          : {}
          ? "f:conditions"
          : 
            ? "."
            : {}
            ? "k:{\"type\":\"Available\"}"
            : 
              ? "."
              : {}
              ? "f:lastTransitionTime"
              : {}
              ? "f:lastUpdateTime"
              : {}
              ? "f:message"
              : {}
              ? "f:reason"
              : {}
              ? "f:status"
              : {}
              ? "f:type"
              : {}
            ? "k:{\"type\":\"Progressing\"}"
            : 
              ? "."
              : {}
              ? "f:lastTransitionTime"
              : {}
              ? "f:lastUpdateTime"
              : {}
              ? "f:message"
              : {}
              ? "f:reason"
              : {}
              ? "f:status"
              : {}
              ? "f:type"
              : {}
          ? "f:observedGeneration"
          : {}
          ? "f:readyReplicas"
          : {}
          ? "f:replicas"
          : {}
          ? "f:updatedReplicas"
          : {}
      manager: kube-controller-manager
      operation: Update
  name: hadoop-namenode
  namespace: default
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: hadoop-namenode
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      creationTimestamp: ~
      labels: 
        app: hadoop-namenode
    spec: 
      containers: 
        - 
          env: 
            - 
              name: CLUSTER_NAME
              valueFrom: 
                configMapKeyRef: 
                  key: CLUSTER_NAME
                  name: hadoop-namenode-config-zpsj
            - 
              name: CORE_CONF_fs_defaultFS
              valueFrom: 
                configMapKeyRef: 
                  key: CORE_CONF_fs_defaultFS
                  name: hadoop-namenode-config-zpsj
            - 
              name: CORE_CONF_hadoop_http_staticuser_user
              valueFrom: 
                configMapKeyRef: 
                  key: CORE_CONF_hadoop_http_staticuser_user
                  name: hadoop-namenode-config-zpsj
            - 
              name: CORE_CONF_hadoop_proxyuser_hue_hosts
              valueFrom: 
                configMapKeyRef: 
                  key: CORE_CONF_hadoop_proxyuser_hue_hosts
                  name: hadoop-namenode-config-zpsj
            - 
              name: CORE_CONF_hadoop_proxyuser_hue_groups
              valueFrom: 
                configMapKeyRef: 
                  key: CORE_CONF_hadoop_proxyuser_hue_groups
                  name: hadoop-namenode-config-zpsj
            - 
              name: CORE_CONF_io_compression_codecs
              valueFrom: 
                configMapKeyRef: 
                  key: CORE_CONF_io_compression_codecs
                  name: hadoop-namenode-config-zpsj
            - 
              name: HDFS_CONF_dfs_webhdfs_enabled
              valueFrom: 
                configMapKeyRef: 
                  key: HDFS_CONF_dfs_webhdfs_enabled
                  name: hadoop-namenode-config-zpsj
            - 
              name: HDFS_CONF_dfs_permissions_enabled
              valueFrom: 
                configMapKeyRef: 
                  key: HDFS_CONF_dfs_permissions_enabled
                  name: hadoop-namenode-config-zpsj
            - 
              name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              valueFrom: 
                configMapKeyRef: 
                  key: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
                  name: hadoop-namenode-config-zpsj
          image: "us.gcr.io/course-project-330721/hadoop-namenode:latest"
          imagePullPolicy: Always
          name: hadoop-namenode-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
