---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hadoop-datanode-config-32dd"
  namespace: "default"
  labels:
    app: "hadoop-datanode"
data:
  SERVICE_PRECONDITION: "\"hadoop-namenode:9870\""
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  CORE_CONF_hadoop_http_staticuser_user: "root"
  CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
  CORE_CONF_hadoop_proxyuser_hue_groups: "*"
  CORE_CONF_io_compression_codecs: "org.apache.hadoop.io.compress.SnappyCodec"
  HDFS_CONF_dfs_webhdfs_enabled: "true"
  HDFS_CONF_dfs_permissions_enabled: "false"
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hadoop-datanode"
  namespace: "default"
  labels:
    app: "hadoop-datanode"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hadoop-datanode"
  template:
    metadata:
      labels:
        app: "hadoop-datanode"
    spec:
      containers:
      - name: "hadoop-datanode-1"
        image: "us.gcr.io/course-project-330721/hadoop-datanode:latest"
        env:
        - name: "SERVICE_PRECONDITION"
          valueFrom:
            configMapKeyRef:
              key: "SERVICE_PRECONDITION"
              name: "hadoop-datanode-config-32dd"
        - name: "CORE_CONF_fs_defaultFS"
          valueFrom:
            configMapKeyRef:
              key: "CORE_CONF_fs_defaultFS"
              name: "hadoop-datanode-config-32dd"
        - name: "CORE_CONF_hadoop_http_staticuser_user"
          valueFrom:
            configMapKeyRef:
              key: "CORE_CONF_hadoop_http_staticuser_user"
              name: "hadoop-datanode-config-32dd"
        - name: "CORE_CONF_hadoop_proxyuser_hue_hosts"
          valueFrom:
            configMapKeyRef:
              key: "CORE_CONF_hadoop_proxyuser_hue_hosts"
              name: "hadoop-datanode-config-32dd"
        - name: "CORE_CONF_hadoop_proxyuser_hue_groups"
          valueFrom:
            configMapKeyRef:
              key: "CORE_CONF_hadoop_proxyuser_hue_groups"
              name: "hadoop-datanode-config-32dd"
        - name: "CORE_CONF_io_compression_codecs"
          valueFrom:
            configMapKeyRef:
              key: "CORE_CONF_io_compression_codecs"
              name: "hadoop-datanode-config-32dd"
        - name: "HDFS_CONF_dfs_webhdfs_enabled"
          valueFrom:
            configMapKeyRef:
              key: "HDFS_CONF_dfs_webhdfs_enabled"
              name: "hadoop-datanode-config-32dd"
        - name: "HDFS_CONF_dfs_permissions_enabled"
          valueFrom:
            configMapKeyRef:
              key: "HDFS_CONF_dfs_permissions_enabled"
              name: "hadoop-datanode-config-32dd"
        - name: "HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check"
          valueFrom:
            configMapKeyRef:
              key: "HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check"
              name: "hadoop-datanode-config-32dd"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hadoop-datanode-hpa-nyld"
  namespace: "default"
  labels:
    app: "hadoop-datanode"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hadoop-datanode"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
