apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-11-28T15:17:30Z"
  generateName: spark-leader-
  labels:
    app: spark-leader
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":7077,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-28T15:17:30Z"
  name: spark-leader-j9ftl
  namespace: default
  resourceVersion: "5777"
  uid: d3caf5ab-7132-41c7-81b5-5e2df611b0f9
spec:
  type: ClusterIP
  ports:
  - port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    app: spark-leader
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
